# NumPy Array Attributes
In NumPy, attributes are properties of NumPy arrays that provide information about the array's shape, size, data type, dimension, and so on.

For example, to get the dimension of an array, we can use the `ndim` attribute.

Here are some of the commonly used NumPy attributes:

| **Attribute** | **Description** |
|---------------|------------------|
| `ndim`        | Returns number of dimensions of the array |
| `size`        | Returns number of elements in the array |
| `dtype`       | Returns data type of elements in the array |
| `shape`       | Returns the size of the array in each dimension |
| `itemsize`    | Returns the size (in bytes) of each element in the array |
| `data`        | Returns the buffer containing actual elements of the array in memory |


In [1]:
import numpy as np

---
### ✅ **1. `array.ndim`** → Number of dimensions

The `ndim` attribute returns the number of dimensions in the numpy array.

In [6]:
array = np.array([[1,2,3],[4,5,6]])
print(array)
print(f"Number of Dimensions: {array.ndim}")

[[1 2 3]
 [4 5 6]]
Number of Dimensions: 2


---
### ✅ **2. `array.shape`** → Tuple representing array dimensions

In NumPy, the `shape` attribute returns a tuple of integers that gives the size of the array in each dimension.

In [14]:
array = np.array([[1,2,3],[4,5,6]])
print(array)
print(f"size of the array in each dimension: {array.shape}")

[[1 2 3]
 [4 5 6]]
size of the array in each dimension: (2, 3)


---
### ✅ **3. `array.size`** → Total number of elements

The `size` attribute returns the total number of elements in the given array.

In [17]:
array = np.array([[1,3,4],[7,2,5]])
print(array)
print(f"number of elements in the given array: {array.size}")

[[1 3 4]
 [7 2 5]]
number of elements in the given array: 6


### ✅ **4. `array.dtype`** → Data type of elements
We can use the `dtype` attribute to check the datatype of a NumPy array.

In [20]:
array = np.array([[2,6,3],[9,5,3]])
print(array)
print(f"datatype of a NumPy array: {array.dtype}")

[[2 6 3]
 [9 5 3]]
datatype of a NumPy array: int64


### ✅ **5. `array.itemsize`** → Size (in bytes) of each element
In NumPy, the `itemsize` attribute determines size (in bytes) of each element in the array. 

In [25]:
array = np.array([78,54,23,45])
print(array)
print(f"size (in bytes) of each element in the array: {array.itemsize}")

[78 54 23 45]
size (in bytes) of each element in the array: 8


---

### ✅ **6. `array.nbytes`** → Total memory (in bytes) consumed


In [26]:
array = np.array([45,34,23,12])
print(array)
print(f"Total memory (in bytes) consumed: {array.nbytes}")

[45 34 23 12]
Total memory (in bytes) consumed: 32


---

### ✅ **7. `array.T`** → Transpose of array


In [34]:
array = np.array([[43,23,65,78],[32,67,54,12]])
print(array)
print(f"Transpose of array:")
print(array.T)

[[43 23 65 78]
 [32 67 54 12]]
Transpose of array:
[[43 32]
 [23 67]
 [65 54]
 [78 12]]


---

### ✅ **8. `array.data`** → returns the buffer containing actual elements of the array in memory


In [38]:
array = np.array([[2,6,4],[4,2,6]])
print(array)
print(array.data)

[[2 6 4]
 [4 2 6]]
