# NumPy Input Output
NumPy offers input/output (I/O) functions for loading and saving data to and from files.

Input/output functions support a variety of file formats, including binary and text formats.

- The binary format is designed for efficient storage and retrieval of large arrays.
- The text format is more human-readable and can be easily edited in a text editor.

#### ✅ NumPy Input/Output Functions Table
| **Function**           | **Description**                                   | **Example / Output**                                   |
|------------------------|---------------------------------------------------|---------------------------------------------------------|
| `np.save()`            | Saves a NumPy array to a `.npy` binary file       | `np.save('data.npy', arr)` → Creates `data.npy`         |
| `np.load()`            | Loads a `.npy` file back into a NumPy array       | `np.load('data.npy')` → Returns the saved array         |
| `np.savetxt()`         | Saves array to a text file (e.g., CSV or TXT)     | `np.savetxt('data.txt', arr)` → Creates plain text file |
| `np.loadtxt()`         | Loads data from a text file into NumPy array      | `np.loadtxt('data.txt')` → Returns the loaded array     |
| `np.genfromtxt()`      | Loads data from text file with missing values     | Handles NaNs: `np.genfromtxt('data.csv', delimiter=',')`|
| `np.fromfile()`        | Reads data from a binary or text file             | `np.fromfile('data.bin', dtype=float)`                  |
| `np.tofile()`          | Writes array to a binary or text file             | `arr.tofile('data.bin')`                                |


In [1]:
import numpy as np

---

### ✅ 1. `np.save()`

**Save array to `.npy` binary file**

Here’s a full explanation of the **`np.save()`** function in NumPy — including its signature, parameters, and example use cases:

Used to **save a NumPy array to a `.npy` binary file** — much faster and more compact than saving to a text file.


### 🔧 **Signature:**

```python
np.save(file, arr, allow_pickle=True, fix_imports=<no value>)
```

## 🔍 **Explanation of Parameters:**

| **Parameter**  | **Type**                      | **Description**                                                                                                                  |
| -------------- | ----------------------------- | -------------------------------------------------------------------------------------------------------------------------------- |
| `file`         | str or file object            | Filename or path where array is saved (e.g. `'data.npy'`). Extension `.npy` is added automatically if not given.                 |
| `arr`          | ndarray                       | The NumPy array to be saved                                                                                                      |
| `allow_pickle` | bool (default=True)           | If True, allows saving object arrays using Python pickles. If False, raises error for object data (e.g. strings, custom objects) |
| `fix_imports`  | bool (default=True if needed) | Used only in Python 2/3 compatibility when using pickle. Usually not needed by users today                                       |

## 📦 **Binary Format (.npy):**

* Compact, fast, and keeps the data type and shape.
* Can store any NumPy array (1D, 2D, structured, complex).

You **must keep `allow_pickle=True`** if saving or loading object data like:

* Strings
* Lists inside arrays
* Custom Python objects

In [21]:
arr = np.array([1, 2, 3, 4, 5])
np.save('my_array.npy', arr)

📝 Creates a binary file named **`my_array.npy`**.

---

### ✅ 2. `np.load()`

**Load array back from `.npy` file**

In [22]:
loade_array = np.load('my_array.npy')
print(loade_array)

[1 2 3 4 5]


---

## 3. `np.savetxt()` — **Function to Save NumPy Arrays to a Text File**

### 🔧 **Function Signature:**

```python
np.savetxt(
    fname,
    X,
    fmt='%.18e',
    delimiter=' ',
    newline='\n',
    header='',
    footer='',
    comments='# ',
    encoding=None,
)
```

Here’s a complete explanation of the **`np.savetxt()` function signature**, its parameters, meaning, and usage — clearly laid out for beginners.

---

## 🔍 Explanation of Parameters:

| **Parameter** | **Meaning**                         | **Use / Example**                                                                  |
| ------------- | ----------------------------------- | ---------------------------------------------------------------------------------- |
| `fname`       | Filename or file handle             | `'data.txt'` or `'data.csv'` or an open file object                                |
| `X`           | Array to save                       | Can be 1D or 2D NumPy array                                                        |
| `fmt`         | Format of each element              | `'%.2f'` (float), `'%d'` (int), `'%s'` (string) <br> Example: `fmt='%s'` for names |
| `delimiter`   | Separator between columns           | `' '` (default), `','` for CSV, `'\t'` for TSV                                     |
| `newline`     | String to end each line             | Default is `'\n'`, can be `'\r\n'` for Windows                                     |
| `header`      | Text to write at the top of file    | Example: `header='Index,Name'`                                                     |
| `footer`      | Text to write at the bottom of file | Example: `footer='-- End of file --'`                                              |
| `comments`    | Prefix for header/footer lines      | Default is `'# '`. Use `comments=''` to remove the hash                            |
| `encoding`    | File encoding (Python 3 only)       | `'utf-8'` (default), `'ascii'`, etc. For non-ASCII characters                      |

---

## 💡 Examples:

### ➤ Save numbers with 2 decimal places:

```python
np.savetxt('data.txt', arr, fmt='%.2f')
```

### ➤ Save with comma delimiter (CSV format):

```python
np.savetxt('data.csv', arr, delimiter=',', fmt='%d')
```

### ➤ Save names with a header and no comment symbol:

```python
np.savetxt('students.csv', names, fmt='%s', header='Name', comments='', delimiter=',')
```

---

## 📌 Notes:

* `np.savetxt()` is mainly for saving **text files** (not binary).
* For more complex files (like Excel), use **Pandas** or other libraries.
* For saving and loading large structured arrays, use `np.save()` / `np.load()`.

In [27]:
array = np.array([[2,5,4],[8,5,8]])
np.savetxt('number.csv',array,fmt='%d',header='Numbers')

In [24]:
names = np.array(['akshit', 'hardik', 'sunny'])
index = np.arange(len(names))
data = np.column_stack((index, names))
np.savetxt('Studentdata.csv', data, fmt='%s', header='Index,Student Name', comments='', delimiter=',')

In [25]:
array = np.array([[1,5,7],[9,5,3]])
np.savetxt('data.txt',array,fmt='%d')

---

### ✅ 4. `np.loadtxt()`

**Load array from a text file**

In [29]:
load_csv = np.loadtxt('number.csv',dtype=int)
print(load_csv)

[[2 5 4]
 [8 5 8]]


In [33]:
load_csv = np.loadtxt('Studentdata.csv', dtype=str, delimiter=',', skiprows=1) # Use skiprows=1 to skip the first line (header)
print(load_csv)

[['0' 'akshit']
 ['1' 'hardik']
 ['2' 'sunny']]


In [35]:
load_txt = np.loadtxt('data.txt',dtype=int)
print(load_txt)

[[1 5 7]
 [9 5 3]]


---

### ✅ 5. `np.genfromtxt()`

**Load from text with missing values**


In [59]:
array = np.array([[1,3,np.nan],[1,np.nan,3],[5,6,7]],dtype=object)
np.savetxt('data_with_missing.txt',array) # save the data

In [60]:
array = np.genfromtxt('data_with_missing.csv',defaultfmt=',') #Load from csv with missing values
print(array)

[[ 1.  3. nan]
 [ 1. nan  3.]]


In [61]:
array = np.genfromtxt('data_with_missing.txt',defaultfmt=',') #Load from txt with missing values
print(array)

[[ 1.  3. nan]
 [ 1. nan  3.]
 [ 5.  6.  7.]]


---
### ✅ 6. `np.tofile()`

**Write array to binary file**


In [68]:
array = np.array([[100,200,300]],dtype=int)
array.tofile('binary_data.bin')


📝 Creates **`binary_data.bin`** (not human-readable, used for raw storage).

---

### ✅ 7. `np.fromfile()`

**Read array from binary file**


In [69]:
array_loaded = np.fromfile('binary_data.bin',dtype=int)
print(array_loaded)

[100 200 300]
