# Numpy Array Indexing
In NumPy, each element in an array is associated with a number. The number is known as an array index.

Let's see an example to demonstrate NumPy array indexing.

![Array Indexing in NumPy](img/numpy-array-index.png)

In the above array, 5 is the 3rd element. However, its index is 2.

This is because the array indexing starts from 0, that is, the first element of the array has index 0, the second element has index 1, and so on.

Now, we'll see how we can access individual items from the array using the index number.

---
### Access Array Elements Using Index
We can use indices to access individual elements of a NumPy array.

Suppose we have a NumPy array:

In [1]:
import numpy as np

In [2]:
array = np.array([1,3,5,7,9])

In [7]:
print(array[0])

1


In [8]:
print(array[2])

5


In [9]:
print(array[4])

9


---
### Modify Array Elements Using Index
We can use indices to change the value of an element in a NumPy array.

In [10]:
print(array)

[1 3 5 7 9]


In [11]:
array[0] = 20
array[2] = 50
array[4] = 80

In [12]:
print(array)

[20  3 50  7 80]


---
### NumPy Negative Array Indexing
NumPy allows negative indexing for its array. The index of -1 refers to the last item, -2 to the second last item and so on.

![NumPy Array Negative Indexing](img/numpy-array-negative-index.png)


In [14]:
array = np.array([1,3,5,7,9])

In [15]:
print(array)

[1 3 5 7 9]


In [17]:
print(array[-1])
print(array[-2])
print(array[-3])
print(array[-4])
print(array[-5])

9
7
5
3
1


---
### Modify Array Elements Using Negative Indexing
Similar to regular indexing, we can also modify array elements using negative indexing. 

In [18]:
print(array)

[1 3 5 7 9]


In [19]:
array[-1] = 90
array[-2] = 70
array[-3] = 50
array[-4] = 30
array[-5] = 10

In [21]:
print(array) # modified array

[10 30 50 70 90]


### 2-D NumPy Array Indexing
Array indexing in NumPy allows us to access and manipulate elements in a 2-D array.

To access an element of array, we need to specify the row index and column index of the element.

In [47]:
array = np.array([[22,43,44],
                 [46,76,23],
                 [32,53,12]])
print(array)

[[22 43 44]
 [46 76 23]
 [32 53 12]]


In [48]:
print(array[0][0])
print(array[0][1])
print(array[0][2])

22
43
44


In [49]:
print(array[1][0])
print(array[1][1])
print(array[1][2])

46
76
23


In [50]:
print(array[2][0])
print(array[2][1])
print(array[2][2])

32
53
12


### Access Row or Column of 2D Array Using Indexing
In NumPy, we can access specific rows or columns of a 2-D array using array indexing.


In [51]:
array = np.array([[22,43,44],
                 [46,76,23],
                 [32,53,12]])
print(array)

[[22 43 44]
 [46 76 23]
 [32 53 12]]


In [56]:
print(array[:][0])
print(array[1][:])
print(array[:][:])

[22 43 44]
[46 76 23]
[[22 43 44]
 [46 76 23]
 [32 53 12]]


### 3-D NumPy Array Indexing
We can also access elements in higher dimensional arrays.

To access an element of a 3D array, we use three indices separated by commas.

- The **first index** refers to the slice
- The **second index** refers to the row
- The **third index** refers to the column.
> **Note:** In 3D arrays, slice is a 2D array that is obtained by taking a subset of the elements in one of the dimensions.

In [65]:
array = np.array([[[12,23,34],
          [45,56,67],
          [78,89,90]],
                  
         [[21,32,43],
          [54,65,76],
          [87,98,91]]])

print(array)

[[[12 23 34]
  [45 56 67]
  [78 89 90]]

 [[21 32 43]
  [54 65 76]
  [87 98 91]]]


In [77]:
print(array[0,0,0]) # first element of first matrix

12


In [79]:
print(array[1,2,2])

91
