# NumPy Array Creation

An array allows us to store a collection of multiple values in a single data structure.

The NumPy array is similar to a list, but with added benefits such as being faster and more memory efficient.

Numpy library provides various methods to work with data. To leverage all those features, we first need to create numpy arrays.

There are multiple techniques to generate arrays in NumPy, and we will explore each of them below.

## 1.Create Array Using Python List

In [1]:
import numpy as np

In [3]:
array = np.array([1,3,5,7,9])
array

array([1, 3, 5, 7, 9])

In [4]:
list = [2,4,6,8,10]
array = np.array(list)
array

array([ 2,  4,  6,  8, 10])

## 2.Create an Array Using `np.zeros()`
***Syntax:***
```python
zeros(shape, dtype=float, order='C', *, like=None)
```

In [5]:
array = np.zeros(5)
array

array([0., 0., 0., 0., 0.])

In [6]:
array = np.zeros((5,),dtype=int)
array

array([0, 0, 0, 0, 0])

In [7]:
array = np.zeros((2,1))
array

array([[0.],
       [0.]])

In [8]:
array = np.zeros((2,2))
array

array([[0., 0.],
       [0., 0.]])

In [9]:
array = np.zeros((4,),dtype=[('x','i4'),('y','i4')])
array

array([(0, 0), (0, 0), (0, 0), (0, 0)], dtype=[('x', '<i4'), ('y', '<i4')])

In [10]:
array = np.zeros(5, dtype=int, order='C', like=None)
array

array([0, 0, 0, 0, 0])

In [11]:
array = np.zeros((5,5),dtype=int)
array

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [12]:
array = np.zeros((2,5))
array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

---

#### Here are **5 beginner-friendly exercises** focused only on `np.zeros()` from NumPy:

### ✅ **Exercise 1: Create a 1D Zero Array**

**Task:**
Create a NumPy array of 10 zeros.

**Expected Output:**

```c
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

```

In [13]:
array = np.zeros((10))
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### ✅ **Exercise 2: Create a 2D Matrix of Zeros**

**Task:**
Create a 3x4 matrix filled with zeros.

**Expected Output:**

```c
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
```

In [14]:
array = np.zeros((3,4))
print(array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### ✅ **Exercise 3: Create a Zero Array with Integer Type**

**Task:**
Create a 5x5 array of zeros with integer type (`dtype=int`).

**Expected Output:**

```c
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
```

In [15]:
array = np.zeros((5,5),dtype=int)
print(array)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


### ✅ **Exercise 4: Create a Zeros Array and Replace Some Values**

**Task:**
Create a 1D array of 8 zeros and replace the first 3 values with 1s.

**Expected Output:**

```c
[1. 1. 1. 0. 0. 0. 0. 0.]
```


In [30]:
array = np.zeros(8)
array[:3]=1
print(array)

[1. 1. 1. 0. 0. 0. 0. 0.]


### ✅ **Exercise 5: Create a 3D Zeros Array**

**Task:**
Create a 3D array of shape (2, 3, 4) filled with zeros.

**Expected Output:**
A 3D array like:

```c
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]
 
 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
```


In [17]:
array = np.zeros((2,3,4))
print(array)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


## 3.Create an Array With `np.arange()`
***Syntax:***
```python
arange([start, stop, step,], dtype=None, *, device=None, like=None)
```

In [50]:
array = np.arange(3) #int
array

array([0, 1, 2])

In [51]:
array = np.arange(3.0) #float
array

array([0., 1., 2.])

In [52]:
array = np.arange(3,7)
array

array([3, 4, 5, 6])

In [54]:
array = np.arange(3,7,2)
array

array([3, 5])

In [55]:
array = np.arange(0, 5, 0.5, dtype=float)
array

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [56]:
array = np.arange(0, 5, 0.5, dtype=int)
array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [58]:
array = np.arange(-3, 3, 0.5).astype(int)
array

array([-3, -2, -2, -1, -1,  0,  0,  0,  1,  1,  2,  2])

In [59]:
array = np.arange(-3, 3, 0.5).astype(float)
array

array([-3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5,  2. ,
        2.5])

---
##### Here are **5 beginner-friendly exercises** using `np.arange()` from NumPy:

### ✅ **Exercise 1: Create a Range of Numbers**

**Task:**
Create an array of numbers from 0 to 9.

**Expected Output:**

```c
[0 1 2 3 4 5 6 7 8 9]
```

In [61]:
array = np.arange(0,10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


### ✅ **Exercise 2: Create Even Numbers Only**

**Task:**
Use `np.arange()` to generate even numbers from 0 to 20.

**Expected Output:**

```c
[ 0  2  4  6  8 10 12 14 16 18]
```

In [62]:
array = np.arange(0,20,2)
print(array)

[ 0  2  4  6  8 10 12 14 16 18]


### ✅ **Exercise 3: Create Array in Reverse Order**

**Task:**
Generate an array from 10 to 1 (excluding 0), in reverse.

**Expected Output:**

```c
[10  9  8  7  6  5  4  3  2  1]
```

In [87]:
array = np.arange(10,0,-1)
print(array)

[10  9  8  7  6  5  4  3  2  1]


### ✅ **Exercise 4: Create Float Range**

**Task:**
Generate an array from 1 to 2 (exclusive) with a step of 0.2.

**Expected Output:**

```c
[1.  1.2 1.4 1.6 1.8]
```

In [88]:
array = np.arange(1,2,0.2)
print(array)

[1.  1.2 1.4 1.6 1.8]


### ✅ **Exercise 5: Count Backward with Step**

**Task:**
Generate values from 50 to 30 (inclusive) decreasing by 5 using `np.arange()`.

**Expected Output:**

```c
[50 45 40 35 30]
```

In [91]:
array = np.arange(50,25,-5)
print(array)

[50 45 40 35 30]


### ✅ **Exercise 6: Create an Array from 5 to 25 with Step 5**

**Task:**
Use `np.arange()` to create an array like:


**Expected Output:**

```c
[5, 10, 15, 20]
```

In [95]:
array = np.arange(5,25,5)
print(array)

[ 5 10 15 20]


### ✅ **Exercise 7: Create Negative Numbers Only**
**Task:**
Create an array from -10 to -1 using `np.arange()`.

**Expected Output:**

```c
[-10 -9 -8 -7 -6 -5 -4 -3 -2 -1]
```


In [101]:
array = np.arange(-10,0)
print(array)

[-10  -9  -8  -7  -6  -5  -4  -3  -2  -1]


## 4.Create an Array With `np.random.rand()`

In [17]:
array = np.random.rand(6)
array

array([0.30875449, 0.21648055, 0.21027831, 0.99135031, 0.71839798,
       0.94458347])

In [18]:
array = np.random.rand(6,2)
array

array([[0.47690657, 0.81437519],
       [0.1767521 , 0.04234023],
       [0.57086101, 0.13710265],
       [0.23595302, 0.28641689],
       [0.97152129, 0.11320812],
       [0.5451667 , 0.91270894]])

In [19]:
array = np.random.rand(6,2,3)
array

array([[[0.36739601, 0.91548697, 0.90980559],
        [0.37458967, 0.19081534, 0.39751931]],

       [[0.19734682, 0.15932239, 0.60811238],
        [0.31293671, 0.326279  , 0.82664145]],

       [[0.08911725, 0.94779509, 0.70462159],
        [0.47904019, 0.02518411, 0.46521766]],

       [[0.48030842, 0.71372146, 0.00409802],
        [0.13112839, 0.97461389, 0.96002253]],

       [[0.4753753 , 0.41786645, 0.38829545],
        [0.74443529, 0.17516842, 0.13845239]],

       [[0.69063566, 0.49959551, 0.90353035],
        [0.934765  , 0.77503155, 0.49883888]]])

---
#### Here are **5 beginner-friendly exercises** using `np.random.rand()` from NumPy:

### ✅ **Exercise 1: Generate a 1D Array of Random Numbers**

**Task:**
Create a 1D array of 5 random numbers between 0 and 1.

**Expected Output Example:**

```c
[0.634, 0.132, 0.875, 0.289, 0.457]
```

In [26]:
array = np.random.rand(5)
round_array = np.round(array,3)
print(round_array)

[0.272 0.759 0.047 0.439 0.471]


### ✅ **Exercise 2: Create a 3x3 Matrix of Random Floats**

**Task:**
Use `np.random.rand()` to create a 3x3 matrix filled with random floats between 0 and 1.

**Expected Output Example:**

```c
[[0.1, 0.6, 0.4],
 [0.8, 0.3, 0.7],
 [0.9, 0.2, 0.5]]
```

In [32]:
array = np.random.rand(3,3)
round_array = np.round(array,1)
print(round_array)

[[0.3 0.1 0.7]
 [0.9 0.4 0.2]
 [0.3 0.3 0.3]]


### ✅ **Exercise 3: Find the Max and Min Values**

**Task:**
Generate an array of 10 random values using `np.random.rand()`. Then find the maximum and minimum values from the array.


In [40]:
array = np.random.rand(10)
print(f"Random Array: {np.round(array,3)}")

max = np.max(array)
min = np.min(array)

print(f"Maximum Value: {np.round(max,3)}")
print(f"Minimum Value: {np.round(min,3)}")

Random Array: [0.904 0.388 0.311 0.369 0.596 0.702 0.789 0.273 0.033 0.831]
Maximum Value: 0.904
Minimum Value: 0.033


### ✅ **Exercise 4: Check Values Greater Than 0.5**

**Task:**
Create an array of 6 random floats using `np.random.rand()`, and print a Boolean array where values greater than 0.5 are marked `True`.

**Expected Output Example:**

```c
[0.3, 0.8, 0.5, 0.9, 0.2, 0.7]
[False, True, False, True, False, True]
```

In [49]:
array = np.random.rand(6)
round_array = np.round(array,1)
print(f"Random Aarry: {round_array}")
bool_array = round_array > 0.5
print(f"Greter then 0.5: {bool_array}")

Random Aarry: [0.3 0.4 0.6 0.  0.7 1. ]
Greter then 0.5: [False False  True False  True  True]



### ✅ **Exercise 5: Reshape Random Values**

**Task:**
Create a flat array of 12 random floats and reshape it into a 4x3 matrix.

**Hint:**

```c
array.reshape(4, 3)
```


In [54]:
array = np.random.rand(12)

matrix = array.reshape(4,3)

print(f"{np.round(matrix,2)}")

[[0.46 0.26 0.58]
 [0.9  0.21 0.53]
 [0.97 0.93 0.5 ]
 [0.33 0.99 0.17]]


## 5.Create an Empty NumPy Array
***Syntax:***
```python
empty(shape, dtype=float, order='C', *, device=None, like=None)
```
Return a new array of given shape and type, without initializing entries.


In [59]:
array = np.empty(4)
array

array([0.7, 0.7, 0.1, 0.4])

In [60]:
array = np.empty([2,2])
array

array([[0.7, 0.7],
       [0.1, 0.4]])

In [61]:
array = np.empty([2,2],dtype=int)
array

array([[4604480259023595110, 4604480259023595110],
       [4591870180066957722, 4600877379321698714]])