# NumPy Array Creation

An array allows us to store a collection of multiple values in a single data structure.

The NumPy array is similar to a list, but with added benefits such as being faster and more memory efficient.

Numpy library provides various methods to work with data. To leverage all those features, we first need to create numpy arrays.

There are multiple techniques to generate arrays in NumPy, and we will explore each of them below.

## 1.Create Array Using Python List

In [14]:
import numpy as np

In [15]:
array = np.array([1,3,5,7,9])
array

array([1, 3, 5, 7, 9])

In [16]:
list = [2,4,6,8,10]
array = np.array(list)
array

array([ 2,  4,  6,  8, 10])

## 2.Create an Array Using `np.zeros()`
***Docstring:***
```python
zeros(shape, dtype=float, order='C', *, like=None)

Return a new array of given shape and type, filled with zeros.

Parameters
----------
shape : int or tuple of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.
        
Examples
--------
```

In [57]:
array = np.zeros(5)
array

array([0., 0., 0., 0., 0.])

In [58]:
array = np.zeros((5,),dtype=int)
array

array([0, 0, 0, 0, 0])

In [59]:
array = np.zeros((2,1))
array

array([[0.],
       [0.]])

In [60]:
array = np.zeros((2,2))
array

array([[0., 0.],
       [0., 0.]])

In [61]:
array = np.zeros((4,),dtype=[('x','i4'),('y','i4')])
array

array([(0, 0), (0, 0), (0, 0), (0, 0)], dtype=[('x', '<i4'), ('y', '<i4')])

In [62]:
array = np.zeros(5, dtype=int, order='C', like=None)
array

array([0, 0, 0, 0, 0])

In [63]:
array = np.zeros((5,5),dtype=int)
array

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [64]:
array = np.zeros((2,5))
array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

---

#### Here are **5 beginner-friendly exercises** focused only on `np.zeros()` from NumPy:

### ✅ **Exercise 1: Create a 1D Zero Array**

**Task:**
Create a NumPy array of 10 zeros.

**Expected Output:**

```c
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

```

In [54]:
array = np.zeros((10))
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### ✅ **Exercise 2: Create a 2D Matrix of Zeros**

**Task:**
Create a 3x4 matrix filled with zeros.

**Expected Output:**

```c
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
```

In [55]:
array = np.zeros((3,4))
print(array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### ✅ **Exercise 3: Create a Zero Array with Integer Type**

**Task:**
Create a 5x5 array of zeros with integer type (`dtype=int`).

**Expected Output:**

```c
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
```

In [56]:
array = np.zeros((5,5),dtype=int)
print(array)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


### ✅ **Exercise 4: Create a Zeros Array and Replace Some Values**

**Task:**
Create a 1D array of 8 zeros and replace the first 3 values with 1s.

**Expected Output:**

```c
[1. 1. 1. 0. 0. 0. 0. 0.]
```


In [65]:
array = np.zeros(8)
array[:3]=1
print(array)

[1. 1. 1. 0. 0. 0. 0. 0.]


### ✅ **Exercise 5: Create a 3D Zeros Array**

**Task:**
Create a 3D array of shape (2, 3, 4) filled with zeros.

**Expected Output:**
A 3D array like:

```c
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]
 
 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
```


In [68]:
array = np.zeros((2,3,4))
print(array)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


## 3.Create an Array With `np.arange()`

In [ ]:
array = np.arange