# NumPy Data Types

A data type is a way to specify the type of data that will be stored in an array.

### NumPy Data Types
NumPy offers a wider range of numerical data types than what is available in Python. Here's the list of most commonly used numeric data types in NumPy:

1. `int8`, `int16`, `int32`, `int64` - signed integer types with different bit sizes
2. `uint8`, `uint16`, `uint32`, `uint64` - unsigned integer types with different bit sizes
3. `float32`, `float64` - floating-point types with different precision levels
4. `complex64`, `complex128` - complex number types with different precision levels

### 1.Check Data Type of a NumPy Array

To check the data type of a NumPy array, we can use the `dtype` attribute. For example,

In [1]:
import numpy as np

In [17]:
array = np.array([1,2,3,4,5])
array.dtype

dtype('int64')

In [18]:
int_array = np.array([1,2,3,4,5])
float_array = np.array([1.2,2.3,3.4,4.5,5.5])
complex_array = np.array([1+2j,2+3j,3+4j])

print(f"Int Array: {int_array}, DataType: {int_array.dtype}")
print(f"Float Array: {float_array}, DataType: {float_array.dtype}")
print(f"Complax Array: {complex_array}, DataType: {complex_array.dtype}")

Int Array: [1 2 3 4 5], DataType: int64
Float Array: [1.2 2.3 3.4 4.5 5.5], DataType: float64
Complax Array: [1.+2.j 2.+3.j 3.+4.j], DataType: complex128


### 2.Creating NumPy Arrays With a Defined Data Type

In [23]:
array = np.array([1,2,3,4],dtype='int8')
print(array)
array.dtype

[1 2 3 4]


dtype('int8')

In [24]:
array1 = np.array([1, 3, 7], dtype='int8')
array2 = np.array([2, 4, 6], dtype='uint16')
array3 = np.array([1.2, 2.3, 3.4], dtype='float32')
array4 = np.array([1+2j, 2+3j, 3+4j], dtype='complex64')

print(array1, array1.dtype)
print(array2, array2.dtype)
print(array3, array3.dtype)
print(array4, array4.dtype)

[1 3 7] int8
[2 4 6] uint16
[1.2 2.3 3.4] float32
[1.+2.j 2.+3.j 3.+4.j] complex64


### 3.NumPy Type Conversion

In [ ]:
int_array = ([1,2,3,4])
float_array = int_array.astype()